'use client'

// import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import "bootstrap/dist/css/bootstrap.min.css";
import StyledComponentsRegistry from './lib/registry'
import Head from 'next/head'
import Link from 'next/link';
import { ReactElement, JSXElementConstructor, ReactNode, ReactPortal, PromiseLikeOfReactNode, useState, useEffect } from 'react';
import { AppWrapper, useAppContext } from '@/context'
import NavMenu from './components/navMenu';

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout(
  props: { children: string | number | boolean | ReactElement<any, string | JSXElementConstructor<any>> | Iterable<ReactNode> | ReactPortal | PromiseLikeOfReactNode | null | undefined; }
) {

  return (
    <html lang="en">
      <StyledComponentsRegistry>
        <Head>
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>
        <body className={inter.className}>
          <AppWrapper>
            <NavMenu />
            {props.children}
          </AppWrapper>
        </body>
      </StyledComponentsRegistry>
    </html>
  )
}
